name: Node.js CI

on:
  push:
    branches: [ "main", "develop", "release/**", "hotfix/**" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js 24.x
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci

      - name: Validar sintaxis del código
        run: npm test
